# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-07-19 19:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='initials',
            field=models.CharField(help_text='Format is AA or AAA', max_length=5, validators=[django.core.validators.RegexValidator('^[A-Z]{2,3}$', message='Use CAPS, 2-3 letters')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='initials',
            field=models.CharField(help_text='Format is AA or AAA', max_length=5, validators=[django.core.validators.RegexValidator('^[A-Z]{2,3}$', message='Use CAPS, 2-3 letters')]),
        ),
    ]
