# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-07-19 13:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edc_pharma', '0002_auto_20161115_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{2,3}$', message='Use CAPS, 2-4 letters')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='dispense',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldispense',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalmedication',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalprotocol',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='hostname_created',
            field=models.CharField(default='pharma', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
